//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionWatcher2._0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NutritionWatcher2._0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (N&apos;Alkoholmentes bor&apos;, 0.5, 0, 1.1, 100), 
        ///(N&apos;Alkoholmentes sör&apos;, 0.2, 0.1, 8.1, 100), 
        ///(N&apos;Almabor&apos;, 0, 0, 5.9, 100), 
        ///(N&apos;Asztali bor&apos;, 0.1, 0, 2.7, 100), 
        ///(N&apos;Barna sör&apos;, 0.3, 0, 2.8, 100), 
        ///(N&apos;Fehérbor&apos;, 0.1, 0, 2.6, 100), 
        ///(N&apos;Gin&apos;, 0, 0, 0, 100), 
        ///(N&apos;Konyak&apos;, 0, 0, 0, 100), 
        ///(N&apos;Likőr&apos;, 0.1, 0.3, 46.8, 100), 
        ///(N&apos;Pálinka&apos;, 0, 0, 0, 100), 
        ///(N&apos;Pezsgő&apos;, 0.2, 0, 1, 100), 
        ///(N&apos;Rum&apos;, 0, 0, 0, 100), 
        ///(N&apos;Sör&apos;, 0.5, 0, 3.6, 100), 
        ///(N&apos;Sütőrum&apos;, 0, 0, 0, 100), 
        ///(N&apos;Tequila&apos;, 0.3, 0.1, 11.3, 100), 
        ///(N&apos;Unic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlValues {
            get {
                return ResourceManager.GetString("SqlValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (N&apos;Alkoholmentes bor&apos;, 0.5, 0, 1.1, 100), 
        ///(N&apos;Alkoholmentes sör&apos;, 0.2, 0.1, 8.1, 100), 
        ///(N&apos;Almabor&apos;, 0, 0, 5.9, 100), 
        ///(N&apos;Asztali bor&apos;, 0.1, 0, 2.7, 100), 
        ///(N&apos;Barna sör&apos;, 0.3, 0, 2.8, 100), 
        ///(N&apos;Fehérbor&apos;, 0.1, 0, 2.6, 100), 
        ///(N&apos;Gin&apos;, 0, 0, 0, 100), 
        ///(N&apos;Konyak&apos;, 0, 0, 0, 100), 
        ///(N&apos;Likőr&apos;, 0.1, 0.3, 46.8, 100), 
        ///(N&apos;Pálinka&apos;, 0, 0, 0, 100), 
        ///(N&apos;Pezsgő&apos;, 0.2, 0, 1, 100), 
        ///(N&apos;Rum&apos;, 0, 0, 0, 100), 
        ///(N&apos;Sör&apos;, 0.5, 0, 3.6, 100), 
        ///(N&apos;Sütőrum&apos;, 0, 0, 0, 100), 
        ///(N&apos;Tequila&apos;, 0.3, 0.1, 11.3, 100), 
        ///(N&apos;Unic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlValuesFirstHalf {
            get {
                return ResourceManager.GetString("SqlValuesFirstHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (N&apos;Kétszersült&apos;, 12, 6.3, 67, 100), 
        ///(N&apos;Kifli&apos;, 9.1, 2.3, 59.1, 100), 
        ///(N&apos;Kuglóf&apos;, 10, 8.7, 58, 100), 
        ///(N&apos;Kukoricás kenyér&apos;, 6.7, 7.4, 43.5, 100), 
        ///(N&apos;Lekváros bukta&apos;, 8, 6, 57, 100), 
        ///(N&apos;Lenmagos barnakenyér&apos;, 10.1, 4.1, 47, 100), 
        ///(N&apos;Magos kenyér&apos;, 11, 6.7, 44.5, 100), 
        ///(N&apos;Magvas barnakenyér&apos;, 10.8, 6.5, 45.8, 100), 
        ///(N&apos;Mazsolás kenyér&apos;, 7.9, 4.4, 48, 100), 
        ///(N&apos;Muffin&apos;, 4.2, 27, 49, 100), 
        ///(N&apos;Olasz kenyér&apos;, 8.8, 3.5, 46.9, 100), 
        ///(N&apos;Palacsinta&apos;, 5, 12, 25, 100), 
        ///(N&apos;Pirítós&apos;, 12, 6.3, 67, 100) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlValuesSecondHalf {
            get {
                return ResourceManager.GetString("SqlValuesSecondHalf", resourceCulture);
            }
        }
    }
}
